module.exports = [
	{ path : /^\/default\.asp$/i, redirect : '/' }
	{ path : '/index.html', redirect : '/' }
	{ path : '/about_us.htm', redirect : '/' }
	{ path : '/store_locator.html', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=14', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=13', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=15', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=22', redirect : '/boys-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCart.php', redirect : '/cart' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=10', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=31', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=32', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=38', redirect : 'http://www.sarasprints.com/SC101_Services/SC101_Shopper/showCatalog.php?menuId=38' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-CTL', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-ctl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=14&itemNum=620G', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-SMP', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-smp-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=23', redirect : '/girls-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-CCP', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-ccp-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=2997B-TDI', redirect : '/dinosaur-pajamas-with-tails--2997-tdi-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=5576A', redirect : '/sara-s-prints-girls-embellished-ruffle-tank-nightgown-5576-nnsl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-CTL', redirect : '/sara-s-prints-girls-ruffle-top-pant-pajama-set-1530-ctl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-CCP', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-ccp-detail' }
	{ path : '/about_us.htm', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-SMP', redirect : '/sara-s-prints-girls-ruffle-top-pant-pajama-set-1530-ctl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-DTR', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-dtr-detail' }
	{ path : '/membership.htm', redirect : '/' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-DBP', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-dbp-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1600G-CTL', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-ctl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=27', redirect : '/boys-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=24', redirect : '/girls-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-HCT', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-hct-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1010G-GWM', redirect : '/sara-s-prints-long-john-pajamas-set-1010-gwm-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-DTR', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-dtr-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-BZY', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-bzy-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-SMP', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-smp-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-NCR', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-ncr-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1010G-GWM', redirect : '/sara-s-prints-long-john-pajamas-set-1010-gwm-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G_SCL', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-scl-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-PKW', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-pkw-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600_BRW', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-brw-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=9', redirect : '/girls-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-CHV', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-chv-detail' }
	{ path : '/size_chart.htm', redirect : '/sizing' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-PNT', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-pnt-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-CHV', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-chv-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-CHV', redirect : '/sara-s-prints-girls-ruffle-top-pant-pajama-set-1530-chv-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=7&itemNum=1600G', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-cbh-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-COMX', redirect : '/sara-s-prints-loose-fitting-pajama-set-1600-comx-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-GWM', redirect : '/sara-s-prints-girls-ruffle-top-pant-pajama-set-1530-gwm-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-PKW', redirect : '/sara-s-prints-girls-puffed-sleeve-nightgown-1505-pkw-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=7&itemNum=1010G-GWM', redirect : '/sara-s-prints-long-john-pajamas-set-1010-gwm-detail' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-PNT', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-LMAW', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Services/SC101_Shopper/showCart.php', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-GNG', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=13&itemNum=620B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-CBH', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1600G-CTL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-SMP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-HCT', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1600G-CCP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1010B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1600B-SMP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=5576', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G_SCL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1010B-TRAS', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1488', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=4900B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=2997B-TDI', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=14&itemNum=671G', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-SMP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1600B-SMP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-RSC', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-GWM', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-DBP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-CCP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1488', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=3&itemNum=1600B-CBH', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-CCR', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-CBH', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-CCP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-BAL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-SMP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCart.php', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=32&itemNum=671G', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=20', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-GWM', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=15', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-BSP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=4&itemNum=4900B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-CTL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1505G-BAL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=5576A', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-LYP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1600G-GNG', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1600G', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=31&itemNum=620B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=8', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=9', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=7', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1600G', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=5', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=4', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=3', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1010G-GWM', redirect : '/shop-pajamas' }
	{ path : '/Testimonials.html', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1505G-PNT', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1600G-CCP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-PNT', redirect : '/shop-pajamas' }
	{ path : '/size_chart.htm', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1010B-TRAS', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1600G-GNG', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600_BRW', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1010G-PDT', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-GWM', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-CTL', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=4900B', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-COMX', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-NCR', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-BZY', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=27&itemNum=1600B-GNG', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1010G-GWM', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showCatalog.php?menuId=20', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-BSP', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=22&itemNum=1600B-CCR', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=23&itemNum=1530G-CHV', redirect : '/shop-pajamas' }
	{ path : '/SC101_Services/SC101_Shopper/showItem.php?menuId=24&itemNum=1530G-LYP', redirect : '/shop-pajamas' }

];
